version: '3.9'
services:
  metabase-app:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - $PWD:/metabase-data
      - $PWD/data:/data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge